apiVersion: apps/v1
kind: Deployment
metadata:
  name: server_keylog_pod
  labels:
    app: server
spec:
  replicas: 1
  selector:
     matchLabels:
        app: server
  template:
     metadata:
       labels:
        app: server
  spec:
  containers:
    - name: server
      image: secops113/server_keylog
      ports:
        - containerPort: 80
        - containerPort: 8080
        - containerPort: 1337
---
apiVersion: apps/v1
kind: Service
metadata:
  name: keylog-service
spec:
  type: NodePort
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    - protocol: TCP
      port: 8080
      targetPort: 8080
    - protocol: TCP
      port: 1337
      targetPort: 1337
      nodeport: